export const productosArte = [
  {
    id: 1,
    titulo: "Pinceles Profesionales",
    precio: 25,
    stock: 50,
    imagen: "pinceles.jpg",
    descripcion:
      "Juego de pinceles de alta calidad para artistas profesionales y principiantes.",
    categoria: "Pintura",
  },
  {
    id: 2,
    titulo: "Acrílicos Premium",
    precio: 40,
    stock: 30,
    imagen: "acrilicos.jpg",
    descripcion: "Set de acrílicos con colores vibrantes y duraderos.",
    categoria: "Pintura",
  },
  {
    id: 3,
    titulo: "Bloc de Dibujo",
    precio: 15,
    stock: 100,
    imagen: "bloc_dibujo.jpg",
    descripcion: "Bloc de papel de alta calidad para dibujos y bocetos.",
    categoria: "Dibujo",
  },
  {
    id: 4,
    titulo: "Lápices de Grafito",
    precio: 20,
    stock: 80,
    imagen: "lapices_grafito.jpg",
    descripcion:
      "Set de lápices de grafito para profesionales, con diferentes grados de dureza.",
    categoria: "Dibujo",
  },
  {
    id: 5,
    titulo: "Caballete de Madera",
    precio: 60,
    stock: 10,
    imagen: "caballete.jpg",
    descripcion:
      "Caballete ajustable de madera de haya, perfecto para pintar o exponer obras.",
    categoria: "Accesorios",
  },
  {
    id: 6,
    titulo: "Paleta de Mezcla",
    precio: 10,
    stock: 25,
    imagen: "paleta_mezcla.jpg",
    descripcion: "Paleta ergonómica para mezclar pinturas acrílicas y óleos.",
    categoria: "Accesorios",
  },
  {
    id: 7,
    titulo: "Óleos Profesionales",
    precio: 45,
    stock: 35,
    imagen: "oleos.jpg",
    descripcion:
      "Set de óleos de alta calidad, perfectos para pintura artística.",
    categoria: "Pintura",
  },
  {
    id: 8,
    titulo: "Pasteles Secos",
    precio: 30,
    stock: 20,
    imagen: "pasteles_secos.jpg",
    descripcion:
      "Caja de pasteles secos suaves, ideales para crear efectos artísticos únicos.",
    categoria: "Dibujo",
  },
  {
    id: 9,
    titulo: "Marco de Madera",
    precio: 50,
    stock: 15,
    imagen: "marco_madera.jpg",
    descripcion: "Marco de madera natural para enmarcar obras de arte.",
    categoria: "Accesorios",
  },
  {
    id: 10,
    titulo: "Lápices de Colores",
    precio: 35,
    stock: 60,
    imagen: "lapices_colores.jpg",
    descripcion:
      "Set de lápices de colores de alta pigmentación, perfectos para ilustraciones detalladas.",
    categoria: "Dibujo",
  },
];
